# Generated by Django 5.2.12 on 2026-04-11 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pantry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'pantries',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilograms'), ('g', 'Grams'), ('l', 'Liters'), ('ml', 'Milliliters'), ('dozen', 'Dozen'), ('pack', 'Pack'), ('bottle', 'Bottle'), ('can', 'Can'), ('bag', 'Bag')], default='pcs', max_length=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('stock', 'In Stock'), ('low', 'Running Low'), ('expired', 'Expired')], default='stock', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pantry_items', to='groceries.category')),
                ('pantry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='groceries.pantry')),
            ],
            options={
                'ordering': ['-added_date'],
            },
        ),
    ]
